### ISSUE TITLE
Error adding gif emote

### ISSUE THREAD

**Issue by ghost** [zakary2841/7tv-bot-for-Discord#2]
![Discord_rPkW5Zajqx](https://user-images.githubusercontent.com/43517263/211666687-01ec107a-cf71-46f9-906f-fb1b8406c43a.png)
Hello, I was able to add some gifs from 7tv with the bot but on one specific one for example I get this error: 
Hybrid command raised an error: Command 'addemote' raised an exception: IndexError: list index out of range
emote in question: https://7tv.app/emotes/638a80bd2efd17dd5e6c838f

**Comment by Zakary2841** [comment]
Are you still having this issue? I tried checking the emote but it was removed. Apologies for the delayed reply. It looks like my notifications weren't set up properly.
